### ISSUE TITLE
Add support for python 3.10

### ISSUE THREAD

**Issue by rainman110** [DLR-SC/tigl-conda#25]
We also should reevaluate, which python versions we still want to support. Currently, we support the four versions
 - 3.6
 - 3.7
 - 3.8
 - 3.9

Adding a fifth version will put more pressure on the CI system, so dropping one (3.6?) might be beneficial.

**Comment by joergbrech** [comment]
I agree. Let's build for a maximum of four Python versions. Which ones should it be? We could pick the most recent ones, e.g. 3.8, 3.9, 3.10, 3.11.

**Comment by rainman110** [comment]
I think we need to figure out, what the tigl users are actually using.

**Comment by joergbrech** [comment]
Ok, so I suppose a good policy would be to kick out end-of-life Python versions. 

That would still leave us with currently five Python versions that must be supported. 3.7 will reach end-of-life soon, but 3.12 is just around the corner...
