### ISSUE TITLE
swig 4.0.2 was released...

### ISSUE THREAD

**Issue by tpaviot** [DLR-SC/tigl-conda#8]
... just a couple of days ago. The dlr-sc swig conda package could be updated

**Comment by rainman110** [comment]
I rebuild swig 4.0.2 today. Closing this issue.

**Comment by tpaviot** [comment]
thank you. I confirm there is a significant performance improvement with large swig files.

**Comment by rainman110** [comment]
Sounds good. Do you mean improved compile time or better performance on runtime?

**Comment by tpaviot** [comment]
I noticed a better performance at compile time (the order of magnitude is 50 mn of total compilation time with the new release, it was around 60mn with the previous version). Well, from 10% to 20% better I would say.
